# Makefile for Docker poser Workspace

docker-build-7.3:
	@docker build . --file Dockerfile-7.3 --tag "orendev/php-base:latest-7.3"

docker-push-7.3:
	@docker push "orendev/php-base:latest-7.3"

docker-build-7.4:
	@docker build . --file Dockerfile-7.4 --tag "orendev/php-base:latest-7.4"

docker-push-7.4:
	@docker push "orendev/php-base:latest-7.4"
